import { useState, useRef } from 'react'
import { CLAUDE_MODEL } from '../config'

const VISION_PROMPT = `You are an emergency triage assistant. Look at this image and assess the emergency situation. DO NOT describe the person's physical appearance (no hair color, skin tone, etc.). Focus ONLY on signs relevant to a medical emergency.

Respond in this exact JSON format:
{
  "risk": "HIGH" | "MEDIUM" | "LOW",
  "summary": "One sentence: what is happening and why it is urgent",
  "signs": [
    "Consciousness: [Unresponsive / Responsive / Unclear]",
    "Breathing: [Not visible / Appears normal / Labored / Unclear]",
    "Scene: [describe substances, pills, bottles, or hazards visible]",
    "Position: [describe body position — face down, on side, etc.]"
  ],
  "actions": [
    "Most urgent action first",
    "Second action",
    "Third action"
  ]
}

Only return the JSON. No other text.`

async function analyzeImage(base64Data, mediaType) {
  const resp = await fetch('/api/claude/v1/messages', {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({
      model: CLAUDE_MODEL,
      max_tokens: 400,
      messages: [{
        role: 'user',
        content: [
          {
            type: 'image',
            source: { type: 'base64', media_type: mediaType, data: base64Data },
          },
          { type: 'text', text: VISION_PROMPT },
        ],
      }],
    }),
  })
  if (!resp.ok) {
    const body = await resp.text().catch(() => '')
    console.error('Vision API', resp.status, body)
    let msg = `${resp.status}`
    try { msg = JSON.parse(body).error?.message || msg } catch { /* ignore */ }
    throw new Error(msg)
  }
  const data = await resp.json()
  return data.content[0].text
}

// Resize to max 1024px, returns { data: base64, mediaType }
function compressToBase64(file) {
  return new Promise((resolve, reject) => {
    const url = URL.createObjectURL(file)
    const img = new Image()
    img.onload = () => {
      URL.revokeObjectURL(url)
      const MAX = 1024
      let { width, height } = img
      if (width > MAX || height > MAX) {
        if (width >= height) { height = Math.round(height * MAX / width); width = MAX }
        else { width = Math.round(width * MAX / height); height = MAX }
      }
      const canvas = document.createElement('canvas')
      canvas.width = width
      canvas.height = height
      canvas.getContext('2d').drawImage(img, 0, 0, width, height)
      const dataUrl = canvas.toDataURL('image/jpeg', 0.82)
      // Canvas may silently fall back to PNG — detect the real type
      const mediaType = dataUrl.startsWith('data:image/png') ? 'image/png' : 'image/jpeg'
      resolve({ data: dataUrl.split(',')[1], mediaType })
    }
    img.onerror = () => {
      // Canvas failed — fall back to raw read, detect type from file
      URL.revokeObjectURL(url)
      const reader = new FileReader()
      reader.onload = () => {
        const dataUrl = reader.result
        const mediaType = dataUrl.startsWith('data:image/png') ? 'image/png' : 'image/jpeg'
        resolve({ data: dataUrl.split(',')[1], mediaType })
      }
      reader.onerror = reject
      reader.readAsDataURL(file)
    }
    img.src = url
  })
}

function buildBriefing(result, timestamp, location) {
  const loc = location
    ? `GPS: ${location.lat.toFixed(5)}, ${location.lng.toFixed(5)}`
    : 'Not captured'
  return `HOSPITAL BRIEFING — SafeReach\n${'─'.repeat(32)}\nTime: ${timestamp}\nLocation: ${loc}\n\nVisual Observation:\n${result}\n\n${'─'.repeat(32)}\n⚠️ AI visual observation only. NOT a medical diagnosis. Patient requires immediate professional evaluation.\n\nGenerated by SafeReach Emergency Response App`
}

export default function CameraScreen({ onBack, onResult, location }) {
  const [preview, setPreview] = useState(null)
  const [file, setFile] = useState(null)
  const [analyzing, setAnalyzing] = useState(false)
  const [result, setResult] = useState(null)
  const [error, setError] = useState(null)
  const [briefingCopied, setBriefingCopied] = useState(false)
  const [timestamp] = useState(new Date().toLocaleString())
  const cameraRef = useRef(null)
  const galleryRef = useRef(null)

  function onFileSelect(e) {
    const f = e.target.files?.[0]
    if (!f) return
    setError(null)
    setResult(null)
    setFile(f)
    setPreview(URL.createObjectURL(f))
  }

  async function analyze() {
    if (!file || analyzing) return
    setAnalyzing(true)
    setError(null)
    try {
      const { data, mediaType } = await compressToBase64(file)
      console.log('Image length:', data.length, 'type:', mediaType)
      const assessment = await analyzeImage(data, mediaType)
      setResult(assessment)
    } catch (err) {
      console.error('Vision error:', err)
      setError(`Analysis failed (${err.message}) — try a clearer photo or retake.`)
    } finally {
      setAnalyzing(false)
    }
  }

  async function copyBriefing() {
    const text = buildBriefing(result, timestamp, location)
    try { await navigator.clipboard.writeText(text); setBriefingCopied(true); setTimeout(() => setBriefingCopied(false), 2200) }
    catch { alert(text) }
  }

  return (
    <div style={s.screen}>
      <div style={s.header}>
        <button style={s.backBtn} onClick={onBack}>
          <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
            <path d="M12 4L6 10L12 16" stroke="#fff" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </button>
        <span style={s.headerTitle}>Symptom Scan</span>
        <div style={{ width: 40 }} />
      </div>

      <div style={s.body}>
        {!preview ? (
          <div style={s.uploadArea}>
            <div style={s.uploadCircle}>
              <svg width="44" height="44" viewBox="0 0 44 44" fill="none">
                <rect x="2" y="8" width="40" height="30" rx="5" stroke="rgba(232,0,13,0.5)" strokeWidth="1.8" />
                <circle cx="22" cy="23" r="8" stroke="rgba(232,0,13,0.5)" strokeWidth="1.8" />
                <circle cx="22" cy="23" r="4" fill="rgba(232,0,13,0.15)" stroke="rgba(232,0,13,0.4)" strokeWidth="1.5" />
                <path d="M15 8L17.5 3H26.5L29 8" stroke="rgba(232,0,13,0.5)" strokeWidth="1.8" strokeLinecap="round" />
                <circle cx="35" cy="14" r="2" fill="rgba(232,0,13,0.4)" />
              </svg>
            </div>
            <h2 style={s.uploadTitle}>Capture for AI Assessment</h2>
            <p style={s.uploadSub}>Take a clear photo of the person's face and upper body for visual analysis</p>

            <div style={s.uploadBtns}>
              <button style={s.uploadBtn} onClick={() => cameraRef.current?.click()}>
                <svg width="18" height="18" viewBox="0 0 18 18" fill="none">
                  <rect x="1" y="4" width="16" height="12" rx="2" stroke="#E8000D" strokeWidth="1.5" />
                  <circle cx="9" cy="10" r="3" stroke="#E8000D" strokeWidth="1.5" />
                  <path d="M6 4L7.5 1.5H10.5L12 4" stroke="#E8000D" strokeWidth="1.5" strokeLinecap="round" />
                </svg>
                Take Photo
              </button>
              <button style={{ ...s.uploadBtn, ...s.uploadBtnSecondary }} onClick={() => galleryRef.current?.click()}>
                <svg width="18" height="18" viewBox="0 0 18 18" fill="none">
                  <rect x="1" y="1" width="16" height="16" rx="3" stroke="#A1A1AA" strokeWidth="1.5" />
                  <circle cx="5.5" cy="5.5" r="1.5" fill="#A1A1AA" />
                  <path d="M1 12L5 8L8 11L12 7L17 12" stroke="#A1A1AA" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
                From Gallery
              </button>
            </div>

            <div style={s.warningNote}>
              ⚠️ Results are visual observations only — not a diagnosis. Always call 911.
            </div>
          </div>
        ) : (
          <div style={s.previewArea}>
            <div style={s.previewCard}>
              <img src={preview} alt="Preview" style={s.previewImg} />
              {analyzing && (
                <div style={s.analyzingOverlay}>
                  <div style={s.spinner} />
                  <p style={s.analyzingText}>Analyzing with AI...</p>
                  <p style={s.analyzingSubText}>Claude Vision is assessing the image</p>
                </div>
              )}
            </div>

            {!result && !analyzing && (
              <div style={s.previewActions}>
                <button style={s.retakeBtn} onClick={() => { setPreview(null); setFile(null) }}>Retake</button>
                <button style={s.analyzeBtn} onClick={analyze}>Analyze with AI →</button>
              </div>
            )}

            {error && (
              <div style={s.errorCard}>⚠️ {error}</div>
            )}

            {result && (() => {
              let parsed = null
              try { parsed = JSON.parse(result.replace(/```json|```/g, '').trim()) } catch { /* raw fallback */ }

              const riskColor = { HIGH: '#E8000D', MEDIUM: '#F59E0B', LOW: '#22C55E' }[parsed?.risk] || '#A1A1AA'
              const riskBg = { HIGH: 'rgba(232,0,13,0.12)', MEDIUM: 'rgba(245,158,11,0.1)', LOW: 'rgba(34,197,94,0.1)' }[parsed?.risk] || 'rgba(255,255,255,0.05)'

              return (
                <div style={s.resultArea}>
                  {parsed ? (
                    <>
                      {/* Risk level banner */}
                      <div style={{ ...s.riskBanner, background: riskBg, border: `1px solid ${riskColor}40` }}>
                        <div style={{ ...s.riskBadge, background: riskColor }}>
                          {parsed.risk === 'HIGH' ? '🚨' : parsed.risk === 'MEDIUM' ? '⚠️' : '✓'} {parsed.risk} RISK
                        </div>
                        <p style={s.riskSummary}>{parsed.summary}</p>
                      </div>

                      {/* Signs */}
                      <div style={s.sectionCard}>
                        <div style={s.sectionTitle}>OBSERVED SIGNS</div>
                        {parsed.signs?.map((sign, i) => (
                          <div key={i} style={s.signRow}>
                            <span style={s.signDot} />
                            <span style={s.signText}>{sign}</span>
                          </div>
                        ))}
                      </div>

                      {/* Actions */}
                      <div style={{ ...s.sectionCard, borderColor: 'rgba(232,0,13,0.2)' }}>
                        <div style={{ ...s.sectionTitle, color: '#E8000D' }}>IMMEDIATE ACTIONS</div>
                        {parsed.actions?.map((action, i) => (
                          <div key={i} style={s.actionRow}>
                            <span style={s.actionNum}>{i + 1}</span>
                            <span style={s.actionText}>{action}</span>
                          </div>
                        ))}
                      </div>
                    </>
                  ) : (
                    /* Fallback: raw text */
                    <div style={s.sectionCard}>
                      <div style={s.sectionTitle}>AI OBSERVATION</div>
                      <p style={s.resultText}>{result}</p>
                    </div>
                  )}

                  <div style={s.warnCard}>
                    ⚠️ Visual observation only — not a medical diagnosis. Always call 911.
                  </div>

                  <div style={s.briefingCard}>
                    <div style={s.briefingHeader}>
                      <span style={s.briefingTitle}>Hospital Briefing</span>
                      <span style={s.briefingSubtitle}>Share with EMS or staff on arrival</span>
                    </div>
                    <button style={s.briefingBtn} onClick={copyBriefing}>
                      {briefingCopied ? '✓ Copied to clipboard' : 'Copy Hospital Briefing'}
                    </button>
                  </div>

                  <div style={s.resultActions}>
                    <button style={s.retakeBtn} onClick={() => { setPreview(null); setFile(null); setResult(null) }}>
                      New Photo
                    </button>
                    <button style={s.saveBtn} onClick={() => onResult(parsed?.summary || result)}>
                      Save &amp; Return
                    </button>
                  </div>
                </div>
              )
            })()}
          </div>
        )}
      </div>

      <input ref={cameraRef} type="file" accept="image/*" capture="environment" onChange={onFileSelect} style={{ display: 'none' }} />
      <input ref={galleryRef} type="file" accept="image/*" onChange={onFileSelect} style={{ display: 'none' }} />
    </div>
  )
}

const s = {
  screen: { display: 'flex', flexDirection: 'column', minHeight: '100svh', background: '#0A0A0A' },
  header: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '12px 14px', paddingTop: 'max(12px, env(safe-area-inset-top))', background: '#111', borderBottom: '1px solid rgba(255,255,255,0.07)', flexShrink: 0 },
  backBtn: { width: 40, height: 40, borderRadius: 12, background: 'rgba(255,255,255,0.07)', border: 'none', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' },
  headerTitle: { fontSize: 16, fontWeight: 700, color: '#fff' },
  body: { flex: 1, overflowY: 'auto', WebkitOverflowScrolling: 'touch' },
  uploadArea: { display: 'flex', flexDirection: 'column', alignItems: 'center', padding: '40px 24px 32px', gap: 18 },
  uploadCircle: { width: 96, height: 96, borderRadius: '50%', background: 'rgba(232,0,13,0.07)', border: '1.5px solid rgba(232,0,13,0.2)', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  uploadTitle: { fontSize: 20, fontWeight: 800, color: '#fff', textAlign: 'center' },
  uploadSub: { fontSize: 14, color: '#52525B', textAlign: 'center', lineHeight: 1.55, maxWidth: 280 },
  uploadBtns: { display: 'flex', flexDirection: 'column', gap: 10, width: '100%' },
  uploadBtn: { width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 10, padding: '15px', background: 'rgba(232,0,13,0.1)', border: '1px solid rgba(232,0,13,0.25)', borderRadius: 14, fontSize: 15, fontWeight: 700, color: '#E8000D', cursor: 'pointer', WebkitTapHighlightColor: 'transparent' },
  uploadBtnSecondary: { background: '#1A1A1A', border: '1px solid rgba(255,255,255,0.1)', color: '#A1A1AA' },
  warningNote: { fontSize: 12, color: '#52525B', textAlign: 'center', lineHeight: 1.5, background: 'rgba(255,255,255,0.03)', borderRadius: 10, padding: '10px 16px', border: '1px solid rgba(255,255,255,0.06)', maxWidth: 300 },
  previewArea: { display: 'flex', flexDirection: 'column', gap: 12, padding: '14px' },
  previewCard: { position: 'relative', borderRadius: 18, overflow: 'hidden', background: '#000' },
  previewImg: { width: '100%', maxHeight: 260, objectFit: 'cover', display: 'block' },
  analyzingOverlay: { position: 'absolute', inset: 0, background: 'rgba(0,0,0,0.75)', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 10 },
  spinner: { width: 36, height: 36, borderRadius: '50%', border: '3px solid rgba(255,255,255,0.15)', borderTopColor: '#E8000D', animation: 'spin 0.8s linear infinite' },
  analyzingText: { color: '#fff', fontSize: 16, fontWeight: 700 },
  analyzingSubText: { color: 'rgba(255,255,255,0.5)', fontSize: 12 },
  previewActions: { display: 'flex', gap: 10 },
  retakeBtn: { flex: 1, padding: '13px', background: 'rgba(255,255,255,0.07)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: 13, fontSize: 14, fontWeight: 600, color: '#A1A1AA', cursor: 'pointer' },
  analyzeBtn: { flex: 2, padding: '13px', background: '#E8000D', border: 'none', borderRadius: 13, fontSize: 15, fontWeight: 700, color: '#fff', cursor: 'pointer', boxShadow: '0 4px 16px rgba(232,0,13,0.35)' },
  errorCard: { background: 'rgba(232,0,13,0.1)', border: '1px solid rgba(232,0,13,0.25)', borderRadius: 12, padding: '12px 14px', fontSize: 13, color: '#E8000D' },
  resultArea: { display: 'flex', flexDirection: 'column', gap: 10 },
  riskBanner: { borderRadius: 16, padding: '14px', animation: 'fade-up 0.25s ease' },
  riskBadge: { display: 'inline-flex', alignItems: 'center', gap: 6, borderRadius: 8, padding: '5px 12px', fontSize: 12, fontWeight: 800, color: '#fff', letterSpacing: '1px', marginBottom: 8 },
  riskSummary: { fontSize: 15, fontWeight: 600, color: '#fff', lineHeight: 1.5, margin: 0 },
  sectionCard: { background: '#161616', borderRadius: 14, padding: '14px', border: '1px solid rgba(255,255,255,0.07)', display: 'flex', flexDirection: 'column', gap: 8, animation: 'fade-up 0.3s ease' },
  sectionTitle: { fontSize: 10, fontWeight: 800, color: '#52525B', letterSpacing: '1.5px', marginBottom: 2 },
  signRow: { display: 'flex', alignItems: 'flex-start', gap: 10 },
  signDot: { width: 6, height: 6, borderRadius: '50%', background: '#52525B', marginTop: 6, flexShrink: 0 },
  signText: { fontSize: 14, color: '#E5E5E5', lineHeight: 1.5 },
  actionRow: { display: 'flex', alignItems: 'flex-start', gap: 10 },
  actionNum: { width: 22, height: 22, borderRadius: '50%', background: '#E8000D', color: '#fff', fontSize: 11, fontWeight: 800, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, marginTop: 1 },
  actionText: { fontSize: 14, color: '#fff', lineHeight: 1.5, fontWeight: 500 },
  resultText: { fontSize: 14, color: '#E5E5E5', lineHeight: 1.6, margin: 0 },
  warnCard: { background: 'rgba(232,0,13,0.08)', border: '1px solid rgba(232,0,13,0.2)', borderRadius: 12, padding: '10px 14px', fontSize: 12, color: '#E8000D', fontWeight: 600, lineHeight: 1.5, animation: 'fade-up 0.3s ease' },
  briefingCard: { background: 'rgba(59,130,246,0.07)', border: '1px solid rgba(59,130,246,0.2)', borderRadius: 14, padding: '14px', animation: 'fade-up 0.35s ease' },
  briefingHeader: { marginBottom: 10 },
  briefingTitle: { fontSize: 14, fontWeight: 700, color: '#3B82F6', display: 'block', marginBottom: 2 },
  briefingSubtitle: { fontSize: 12, color: '#3B82F6', opacity: 0.7 },
  briefingBtn: { width: '100%', padding: '12px', background: '#1D4ED8', border: 'none', borderRadius: 10, fontSize: 14, fontWeight: 700, color: '#fff', cursor: 'pointer' },
  resultActions: { display: 'flex', gap: 10, paddingBottom: 8 },
  saveBtn: { flex: 2, padding: '13px', background: '#E8000D', border: 'none', borderRadius: 13, fontSize: 15, fontWeight: 700, color: '#fff', cursor: 'pointer', boxShadow: '0 4px 16px rgba(232,0,13,0.3)' },
}
