import { useState, useEffect, useRef, useCallback } from 'react'
import ChatInterface from '../components/ChatInterface'
import {
  getSession, updateSession, markVoicePlayed, calculateETA,
} from '../utils/session'

function elapsed(secs) {
  return `${String(Math.floor(secs / 60)).padStart(2, '0')}:${String(secs % 60).padStart(2, '0')}`
}

function loadEmergencyContacts() {
  try { return JSON.parse(localStorage.getItem('sr_contacts') || '[]').filter(c => c.phone) }
  catch { return [] }
}

function buildEMS({ userName, location, chatHistory, naloxoneGiven, timestamp }) {
  const symptoms = chatHistory
    .filter(m => m.role === 'user').map(m => m.content).join('; ') || 'None recorded'
  const loc = location
    ? `${location.lat.toFixed(5)}, ${location.lng.toFixed(5)} — https://maps.google.com/?q=${location.lat},${location.lng}`
    : 'Not available'
  return `EMS BRIEFING — SafeReach\n${'─'.repeat(32)}\nPatient: ${userName || 'Unknown'}\nAlert time: ${timestamp}\nLocation: ${loc}\nSymptoms: ${symptoms}\nNaloxone: ${naloxoneGiven ? 'YES' : 'NO / Unknown'}\n${'─'.repeat(32)}\nGenerated by SafeReach`
}

export default function EmergencyActiveScreen({
  sessionCode, onEnd, onOpenCamera,
  chatHistory, onUpdateChatHistory,
  naloxoneGiven, onToggleNaloxone,
  userName, location, onUpdateLocation, visionResult,
}) {
  const [secs, setSecs] = useState(0)
  const [alertTime] = useState(new Date().toLocaleString())
  const [familyMembers, setFamilyMembers] = useState([])
  const [voiceNotif, setVoiceNotif] = useState(null)
  const [gpsLoading, setGpsLoading] = useState(false)
  const [gpsError, setGpsError] = useState(null)
  const [showEMS, setShowEMS] = useState(false)
  const [copied, setCopied] = useState(false)
  const [codeCopied, setCodeCopied] = useState(false)
  const [showVision, setShowVision] = useState(!!visionResult)
  const [alertShared, setAlertShared] = useState(false)
  const [showAlertModal, setShowAlertModal] = useState(false)
  const [alertMessage, setAlertMessage] = useState('')
  const [alertContacts, setAlertContacts] = useState([])

  // Refs for latest values inside the poll interval
  const locationRef = useRef(location)
  const chatHistoryRef = useRef(chatHistory)
  const naloxoneRef = useRef(naloxoneGiven)
  const prevFamilyCount = useRef(0)
  const prevVoiceCount = useRef(0)
  const prevFamMsgCount = useRef(0)

  useEffect(() => { locationRef.current = location }, [location])
  useEffect(() => { chatHistoryRef.current = chatHistory }, [chatHistory])
  useEffect(() => { naloxoneRef.current = naloxoneGiven }, [naloxoneGiven])
  useEffect(() => { if (visionResult) setShowVision(true) }, [visionResult])

  // Timer
  useEffect(() => {
    const t = setInterval(() => setSecs(s => s + 1), 1000)
    return () => clearInterval(t)
  }, [])

  // Session poll — write state + react to family joins
  useEffect(() => {
    if (!sessionCode) return

    function tick() {
      const session = getSession(sessionCode)
      if (!session) return

      const members = session.familyMembers || []
      const voiceMsgs = session.voiceMessages || []
      const famMsgs = session.familyMessages || []

      // New family member joined
      if (members.length > prevFamilyCount.current) {
        const newMember = members[members.length - 1]
        setFamilyMembers([...members])
        let msgText
        if (locationRef.current && newMember.location) {
          const { distance, eta } = calculateETA(locationRef.current, newMember.location)
          msgText = `${newMember.name} just joined. They're ${distance} miles away — about ${eta} minutes. Help is coming.`
        } else {
          msgText = `${newMember.name} just joined your session. They're on their way to help you.`
        }
        const aiMsg = { role: 'assistant', content: msgText, id: `fam_${Date.now()}` }
        onUpdateChatHistory(prev => [...prev, aiMsg])
        if ('speechSynthesis' in window) {
          const u = new SpeechSynthesisUtterance(msgText)
          u.rate = 0.9
          window.speechSynthesis.speak(u)
        }
      } else {
        setFamilyMembers([...members])
      }
      prevFamilyCount.current = members.length

      // Unplayed voice messages
      const unplayed = voiceMsgs.filter(m => !m.played)
      if (unplayed.length > prevVoiceCount.current) {
        const msg = unplayed[unplayed.length - 1]
        try { new Audio(msg.audio).play() } catch { /* ignore */ }
        markVoicePlayed(sessionCode, msg.timestamp)
        setVoiceNotif({ from: msg.from })
        setTimeout(() => setVoiceNotif(null), 4500)
      }
      prevVoiceCount.current = unplayed.length

      // Family text messages
      if (famMsgs.length > prevFamMsgCount.current) {
        const newMsg = famMsgs[famMsgs.length - 1]
        const aiMsg = { role: 'assistant', content: `${newMsg.from}: "${newMsg.text}"`, id: `fmsg_${Date.now()}` }
        onUpdateChatHistory(prev => [...prev, aiMsg])
      }
      prevFamMsgCount.current = famMsgs.length

      // Write latest state to session
      updateSession(sessionCode, {
        victimLocation: locationRef.current,
        victimLastSeen: Date.now(),
        chatHistory: chatHistoryRef.current,
        naloxoneGiven: naloxoneRef.current,
      })
    }

    tick()
    const interval = setInterval(tick, 5000)
    return () => clearInterval(interval)
  }, [sessionCode]) // eslint-disable-line

  const getLocation = useCallback(() => {
    if (location) return Promise.resolve(location)
    return new Promise((resolve, reject) => {
      if (!navigator.geolocation) { reject(new Error('Geolocation unavailable')); return }
      navigator.geolocation.getCurrentPosition(
        p => { const l = { lat: p.coords.latitude, lng: p.coords.longitude }; onUpdateLocation(l); resolve(l) },
        () => reject(new Error('Location denied')),
        { timeout: 8000 }
      )
    })
  }, [location, onUpdateLocation])

  async function handleAlert() {
    setGpsLoading(true)
    setGpsError(null)
    setAlertShared(false)
    let loc = location
    try { loc = await getLocation() } catch { setGpsError('Location unavailable — sharing without GPS.') }
    finally { setGpsLoading(false) }

    const params = new URLSearchParams({ name: userName || 'Someone' })
    if (loc) { params.set('lat', loc.lat); params.set('lng', loc.lng) }
    const joinLink = `${window.location.origin}/join/${sessionCode}?${params}`
    const mapsLink = loc ? `https://maps.google.com/?q=${loc.lat},${loc.lng}` : null
    const name = userName || 'Someone'
    const text = [
      `🚨 EMERGENCY ALERT 🚨`,
      `${name} may need help RIGHT NOW.`,
      '',
      mapsLink ? `📍 Live location: ${mapsLink}` : '📍 Location unavailable.',
      `🔴 Join live session: ${joinLink}`,
      `🔑 Code: ${sessionCode}`,
      '',
      'Please respond immediately or call 911.',
    ].join('\n')

    const contacts = loadEmergencyContacts()

    if (contacts.length === 0) {
      // No saved contacts — share sheet or SMS
      if (navigator.share) {
        try { await navigator.share({ title: 'EMERGENCY — SafeReach', text }); setAlertShared(true) }
        catch { /* cancelled */ }
      } else {
        setAlertShared(true)
        window.location.href = `sms:?&body=${encodeURIComponent(text)}`
      }
      return
    }

    // Try sending automatically via SignalWire
    try {
      const resp = await fetch('/api/alert', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ contacts, message: text }),
      })
      if (resp.ok) {
        const { sent, failed } = await resp.json()
        setAlertShared(true)
        if (failed.length) setGpsError(`Sent to ${sent.length}, failed: ${failed.length}`)
        return
      }
    } catch { /* server not running — fall through to SMS */ }

    // Fallback: SMS picker
    setAlertMessage(text)
    setAlertContacts(contacts)
    setShowAlertModal(true)
  }

  async function shareAll() {
    setShowAlertModal(false)
    if (navigator.share) {
      try { await navigator.share({ title: 'EMERGENCY — SafeReach', text: alertMessage }); setAlertShared(true) }
      catch { /* cancelled */ }
    } else {
      setAlertShared(true)
      window.location.href = `sms:?&body=${encodeURIComponent(alertMessage)}`
    }
  }

  function textContact(contact) {
    window.location.href = `sms:${contact.phone}?&body=${encodeURIComponent(alertMessage)}`
    setAlertShared(true)
  }

  async function copyCode() {
    try { await navigator.clipboard.writeText(sessionCode) } catch { /* ignore */ }
    setCodeCopied(true)
    setTimeout(() => setCodeCopied(false), 2000)
  }

  async function shareCode() {
    const msg = `Join my SafeReach emergency session. Open the app and enter code: ${sessionCode}`
    if (navigator.share) {
      try { await navigator.share({ title: 'Join my emergency session', text: msg }) } catch { /* cancelled */ }
    } else {
      try { await navigator.clipboard.writeText(msg) } catch { /* ignore */ }
    }
  }

  async function copyEMS() {
    const report = buildEMS({ userName, location, chatHistory, naloxoneGiven, timestamp: alertTime })
    try { await navigator.clipboard.writeText(report); setCopied(true); setTimeout(() => setCopied(false), 2200) }
    catch { alert(report) }
  }

  const codeChars = (sessionCode || '------').split('')

  return (
    <div style={s.screen}>
      {/* Voice notification */}
      {voiceNotif && (
        <div style={s.voiceNotif}>
          <span>🎤</span>
          <span>Voice message from <strong>{voiceNotif.from}</strong> — playing</span>
        </div>
      )}

      {/* Header */}
      <div style={s.header}>
        <div style={s.headerLeft}>
          <span style={s.pulse} />
          <span style={s.headerTitle}>EMERGENCY ACTIVE</span>
        </div>
        <div style={s.headerRight}>
          <span style={s.timer}>{elapsed(secs)}</span>
          <button style={s.endBtn} onClick={onEnd}>END</button>
        </div>
      </div>

      <div style={s.scrollArea}>
        {/* Family code card */}
        <div style={s.codeCard}>
          <div style={s.codeCardTop}>
            <div>
              <div style={s.codeCardLabel}>FAMILY CODE</div>
              <div style={s.codeCardSub}>Share with loved ones to join this session</div>
            </div>
            <div style={s.memberBadge}>
              <span style={{ ...s.memberDot, background: familyMembers.length > 0 ? '#22C55E' : '#52525B' }} />
              <span style={s.memberCount}>{familyMembers.length} connected</span>
            </div>
          </div>

          <div style={s.codeBoxes}>
            {codeChars.map((c, i) => (
              <div key={i} style={s.codeBox}>{c}</div>
            ))}
          </div>

          <div style={s.codeActions}>
            <button style={s.codeBtn} onClick={copyCode}>
              {codeCopied ? '✓ Copied' : 'Copy Code'}
            </button>
            <button style={{ ...s.codeBtn, ...s.codeBtnOutline }} onClick={shareCode}>
              Share
            </button>
          </div>
        </div>

        {/* Alert status */}
        {alertShared && !gpsError && <div style={s.alertSharedBanner}>✓ Alert shared</div>}
        {gpsError && <div style={s.gpsError}>{gpsError}</div>}

        {/* Action bar */}
        <div style={s.actionBar}>
          <button style={s.actionBtn} onClick={handleAlert} disabled={gpsLoading}>
            <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
              <path d="M10 1L2.5 16.5H17.5L10 1Z" stroke="#E8000D" strokeWidth="1.6" fill="rgba(232,0,13,0.1)" strokeLinejoin="round" />
              <line x1="10" y1="8" x2="10" y2="12" stroke="#E8000D" strokeWidth="1.5" strokeLinecap="round" />
              <circle cx="10" cy="14.5" r="0.8" fill="#E8000D" />
            </svg>
            <span style={s.actionLabel}>{gpsLoading ? 'Getting location...' : alertShared ? 'Alert shared ✓' : 'Alert Contacts'}</span>
          </button>

          <button style={s.actionBtn} onClick={onOpenCamera}>
            <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
              <rect x="1.5" y="5" width="17" height="13" rx="2.5" stroke="#E8000D" strokeWidth="1.5" />
              <circle cx="10" cy="11.5" r="3.5" stroke="#E8000D" strokeWidth="1.5" />
              <path d="M7 5L8.5 2H11.5L13 5" stroke="#E8000D" strokeWidth="1.5" strokeLinecap="round" />
            </svg>
            <span style={s.actionLabel}>Scan Symptoms</span>
          </button>

          <button style={s.actionBtn} onClick={() => setShowEMS(true)}>
            <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
              <rect x="3.5" y="1.5" width="13" height="17" rx="2" stroke="#E8000D" strokeWidth="1.5" />
              <line x1="7" y1="7" x2="13" y2="7" stroke="#E8000D" strokeWidth="1.3" strokeLinecap="round" />
              <line x1="7" y1="10.5" x2="13" y2="10.5" stroke="#E8000D" strokeWidth="1.3" strokeLinecap="round" />
              <line x1="7" y1="14" x2="10" y2="14" stroke="#E8000D" strokeWidth="1.3" strokeLinecap="round" />
            </svg>
            <span style={s.actionLabel}>EMS Report</span>
          </button>
        </div>

        {/* Naloxone toggle */}
        <div style={s.naloxoneRow}>
          <span style={s.naloxoneLabel}>Naloxone administered?</span>
          <button
            style={{ ...s.naloxoneToggle, background: naloxoneGiven ? '#22C55E' : '#222' }}
            onClick={onToggleNaloxone}
          >
            <span style={{ ...s.naloxoneThumb, transform: naloxoneGiven ? 'translateX(22px)' : 'translateX(2px)' }} />
          </button>
          <span style={{ fontSize: 12, fontWeight: 600, color: naloxoneGiven ? '#22C55E' : '#52525B' }}>
            {naloxoneGiven ? 'YES' : 'NO'}
          </span>
        </div>

        {/* Vision result */}
        {showVision && visionResult && (
          <div style={s.visionCard}>
            <div style={s.visionHeader}>
              <span style={s.visionTitle}>👁 Visual Assessment</span>
              <button style={s.visionClose} onClick={() => setShowVision(false)}>×</button>
            </div>
            <p style={s.visionText}>{visionResult}</p>
            <p style={s.visionWarn}>⚠️ Visual observation only — not a medical diagnosis. Always call 911.</p>
          </div>
        )}
      </div>

      {/* Chat */}
      <ChatInterface chatHistory={chatHistory} onUpdateChatHistory={onUpdateChatHistory} />

      {/* Alert Contacts Modal */}
      {showAlertModal && (
        <div style={s.overlay} onClick={() => setShowAlertModal(false)}>
          <div style={s.modal} onClick={e => e.stopPropagation()}>
            <div style={s.modalHeader}>
              <span style={s.modalTitle}>Alert Contacts</span>
              <button style={s.modalClose} onClick={() => setShowAlertModal(false)}>
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                  <path d="M2 2l10 10M12 2L2 12" stroke="#A1A1AA" strokeWidth="1.8" strokeLinecap="round" />
                </svg>
              </button>
            </div>

            <p style={s.alertModalNote}>
              Opens your SMS app — tap <strong style={{ color: '#fff' }}>Send</strong> to deliver
            </p>

            <div style={s.alertContactList}>
              {alertContacts.map(c => (
                <button key={c.id} style={s.alertContactRow} onClick={() => textContact(c)}>
                  <div style={s.alertContactAvatar}>
                    <span style={s.alertContactInitial}>{c.name[0].toUpperCase()}</span>
                  </div>
                  <div style={s.alertContactInfo}>
                    <span style={s.alertContactName}>{c.name}</span>
                    <span style={s.alertContactMeta}>{c.relation ? `${c.relation} · ` : ''}{c.phone}</span>
                  </div>
                  <span style={s.alertContactCta}>Text →</span>
                </button>
              ))}
            </div>

            <button style={s.shareAllBtn} onClick={shareAll}>
              Share to all (copy / share sheet)
            </button>
          </div>
        </div>
      )}

      {/* EMS Report Modal */}
      {showEMS && (
        <div style={s.overlay} onClick={() => setShowEMS(false)}>
          <div style={s.modal} onClick={e => e.stopPropagation()}>
            <div style={s.modalHeader}>
              <span style={s.modalTitle}>EMS Report</span>
              <button style={s.modalClose} onClick={() => setShowEMS(false)}>
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                  <path d="M2 2l10 10M12 2L2 12" stroke="#A1A1AA" strokeWidth="1.8" strokeLinecap="round" />
                </svg>
              </button>
            </div>
            <pre style={s.emsText}>{buildEMS({ userName, location, chatHistory, naloxoneGiven, timestamp: alertTime })}</pre>
            <button style={s.copyEMSBtn} onClick={copyEMS}>
              {copied ? '✓ Copied to clipboard' : 'Copy to Clipboard'}
            </button>
            <p style={s.emsNote}>Show or read this to EMS / hospital on arrival</p>
          </div>
        </div>
      )}
    </div>
  )
}

const s = {
  screen: { display: 'flex', flexDirection: 'column', height: '100svh', background: '#0A0A0A', overflow: 'hidden' },
  voiceNotif: { background: 'rgba(34,197,94,0.12)', border: '1px solid rgba(34,197,94,0.25)', padding: '8px 16px', display: 'flex', gap: 8, alignItems: 'center', fontSize: 13, color: '#22C55E', fontWeight: 500, flexShrink: 0, animation: 'fade-up 0.25s ease' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: '#1A0000', borderBottom: '1px solid rgba(232,0,13,0.3)', padding: '10px 16px', flexShrink: 0 },
  headerLeft: { display: 'flex', alignItems: 'center', gap: 8 },
  pulse: { width: 10, height: 10, borderRadius: '50%', background: '#E8000D', display: 'inline-block', boxShadow: '0 0 8px #E8000D', animation: 'pulse-dot 1s ease-in-out infinite' },
  headerTitle: { fontSize: 12, fontWeight: 800, color: '#E8000D', letterSpacing: '1.5px' },
  headerRight: { display: 'flex', alignItems: 'center', gap: 10 },
  timer: { fontVariantNumeric: 'tabular-nums', fontSize: 15, fontWeight: 700, color: '#fff', letterSpacing: '1px' },
  endBtn: { background: 'rgba(255,255,255,0.08)', color: '#A1A1AA', border: '1px solid rgba(255,255,255,0.12)', borderRadius: 8, padding: '5px 12px', fontSize: 11, fontWeight: 700, letterSpacing: '0.5px', cursor: 'pointer' },
  scrollArea: { overflowY: 'auto', flexShrink: 0, maxHeight: '42vh', WebkitOverflowScrolling: 'touch' },
  codeCard: { margin: '10px 12px 0', padding: '14px 14px 12px', background: '#161616', borderRadius: 16, border: '1px solid rgba(232,0,13,0.2)' },
  codeCardTop: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
  codeCardLabel: { fontSize: 10, fontWeight: 800, color: '#E8000D', letterSpacing: '1.5px', marginBottom: 2 },
  codeCardSub: { fontSize: 11, color: '#52525B' },
  memberBadge: { display: 'flex', alignItems: 'center', gap: 5, background: 'rgba(255,255,255,0.05)', borderRadius: 20, padding: '4px 8px' },
  memberDot: { width: 7, height: 7, borderRadius: '50%', display: 'inline-block' },
  memberCount: { fontSize: 11, color: '#A1A1AA', fontWeight: 600 },
  codeBoxes: { display: 'flex', gap: 5, justifyContent: 'center', marginBottom: 12 },
  codeBox: { width: 42, height: 52, background: '#0A0A0A', border: '1.5px solid rgba(232,0,13,0.35)', borderRadius: 10, display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'ui-monospace, monospace', fontSize: 22, fontWeight: 800, color: '#fff', letterSpacing: '1px' },
  codeActions: { display: 'flex', gap: 8 },
  codeBtn: { flex: 1, padding: '9px', background: '#E8000D', border: 'none', borderRadius: 10, fontSize: 13, fontWeight: 700, color: '#fff', cursor: 'pointer' },
  codeBtnOutline: { background: 'transparent', border: '1px solid rgba(232,0,13,0.3)', color: '#E8000D' },
  alertSharedBanner: { margin: '6px 12px 0', background: 'rgba(34,197,94,0.1)', border: '1px solid rgba(34,197,94,0.25)', borderRadius: 8, padding: '7px 12px', fontSize: 12, color: '#22C55E', fontWeight: 600 },
  gpsError: { margin: '6px 12px 0', background: 'rgba(245,158,11,0.1)', border: '1px solid rgba(245,158,11,0.25)', borderRadius: 8, padding: '7px 12px', fontSize: 12, color: '#F59E0B' },
  actionBar: { display: 'flex', gap: 8, padding: '10px 12px 0' },
  actionBtn: { flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 5, padding: '10px 6px', background: '#161616', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 14, cursor: 'pointer', WebkitTapHighlightColor: 'transparent' },
  actionLabel: { fontSize: 10.5, fontWeight: 600, color: '#A1A1AA', textAlign: 'center', lineHeight: 1.2 },
  naloxoneRow: { display: 'flex', alignItems: 'center', gap: 10, padding: '10px 14px', margin: '8px 12px 0', background: '#161616', borderRadius: 12, border: '1px solid rgba(255,255,255,0.06)' },
  naloxoneLabel: { flex: 1, fontSize: 13, color: '#A1A1AA', fontWeight: 500 },
  naloxoneToggle: { width: 46, height: 26, borderRadius: 13, border: 'none', cursor: 'pointer', position: 'relative', transition: 'background 0.2s', flexShrink: 0 },
  naloxoneThumb: { position: 'absolute', top: 3, width: 20, height: 20, borderRadius: '50%', background: '#fff', transition: 'transform 0.2s', boxShadow: '0 1px 4px rgba(0,0,0,0.4)' },
  visionCard: { margin: '8px 12px 0', padding: '12px', background: 'rgba(245,158,11,0.06)', border: '1px solid rgba(245,158,11,0.2)', borderRadius: 12, animation: 'fade-up 0.3s ease' },
  visionHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  visionTitle: { fontSize: 12, fontWeight: 700, color: '#F59E0B', letterSpacing: '0.5px' },
  visionClose: { background: 'none', border: 'none', color: '#52525B', fontSize: 18, cursor: 'pointer', lineHeight: 1 },
  visionText: { fontSize: 13, color: '#E5E5E5', lineHeight: 1.55, marginBottom: 6 },
  visionWarn: { fontSize: 11, color: '#E8000D', fontWeight: 600, lineHeight: 1.4 },
  overlay: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', display: 'flex', alignItems: 'flex-end', zIndex: 100 },
  modal: { width: '100%', maxWidth: 390, margin: '0 auto', background: '#161616', borderRadius: '20px 20px 0 0', padding: '20px', animation: 'slide-up 0.28s ease', maxHeight: '80svh', overflowY: 'auto' },
  modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 },
  modalTitle: { fontSize: 17, fontWeight: 700, color: '#fff' },
  modalClose: { width: 30, height: 30, borderRadius: '50%', background: 'rgba(255,255,255,0.08)', border: 'none', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' },
  emsText: { fontFamily: 'ui-monospace, monospace', fontSize: 12, lineHeight: 1.7, color: '#A1A1AA', background: '#0A0A0A', padding: '12px', borderRadius: 10, border: '1px solid rgba(255,255,255,0.07)', whiteSpace: 'pre-wrap', wordBreak: 'break-all', marginBottom: 14 },
  copyEMSBtn: { width: '100%', background: '#E8000D', color: '#fff', border: 'none', borderRadius: 12, padding: '13px', fontSize: 15, fontWeight: 700, cursor: 'pointer', marginBottom: 8 },
  emsNote: { fontSize: 12, color: '#52525B', textAlign: 'center' },
  alertModalNote: { fontSize: 12, color: '#52525B', marginBottom: 14, lineHeight: 1.5 },
  alertContactList: { display: 'flex', flexDirection: 'column', gap: 8, marginBottom: 12 },
  alertContactRow: { display: 'flex', alignItems: 'center', gap: 12, background: '#0A0A0A', borderRadius: 13, padding: '12px 14px', border: '1px solid rgba(232,0,13,0.2)', cursor: 'pointer', width: '100%', textAlign: 'left', WebkitTapHighlightColor: 'transparent' },
  alertContactAvatar: { width: 38, height: 38, borderRadius: '50%', background: 'rgba(232,0,13,0.15)', border: '1px solid rgba(232,0,13,0.25)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  alertContactInitial: { fontSize: 16, fontWeight: 700, color: '#E8000D' },
  alertContactInfo: { flex: 1, display: 'flex', flexDirection: 'column', gap: 2 },
  alertContactName: { fontSize: 14, fontWeight: 600, color: '#fff' },
  alertContactMeta: { fontSize: 11, color: '#52525B' },
  alertContactCta: { fontSize: 13, fontWeight: 700, color: '#E8000D', flexShrink: 0 },
  shareAllBtn: { width: '100%', padding: '13px', background: 'rgba(255,255,255,0.07)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: 12, fontSize: 14, fontWeight: 600, color: '#A1A1AA', cursor: 'pointer', WebkitTapHighlightColor: 'transparent' },
}
